// components/Layout.jsx

import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";
import { Store } from "../utils/Store";

const OffcanvasContent = dynamic(() => import("./OffCanvasContent"), {
  ssr: false,
});

export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;

  const [cartItemsCount, setCartItemsCount] = useState(0);

  useEffect(() => {
    // Verifica si cart y cartItems están definidos antes de usar reduce
    if (cart && cart.cartItems) {
      setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
    }
  }, [cart]);

  const openOffcanvas = async () => {
    try {
      if (typeof window !== "undefined" && !window.bootstrapLoaded) {
        const bootstrap = await import(
          "bootstrap/dist/js/bootstrap.bundle.min.js"
        );
        console.log("Bootstrap loaded");
        window.bootstrap = bootstrap;
        window.bootstrapLoaded = true;
      }

      if (typeof window !== "undefined" && window.bootstrap) {
        const offcanvas = new window.bootstrap.Offcanvas(
          document.getElementById("offcanvasRight")
        );
        offcanvas.show();
      }
    } catch (error) {
      console.error("Error loading Bootstrap:", error);
    }
  };

  return (
    <div>
      <Head>
        <title>Power Sport - Official Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <Link className="navbar-brand" href="/">
            Storage
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                <a href="#" className="nav-link" onClick={openOffcanvas}>
                  Cart{" "}
                  <span className="text-white bg-danger rounded p-1">
                    {cartItemsCount}
                  </span>{" "}
                </a>
              </li>

              <li className="nav-item">
                <Link className="nav-link" href="">
                  Others
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <main>{children}</main>

      <OffcanvasContent />
    </div>
  );
}
