// components/Layout.jsx

import React, { useContext, useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic"; // Importa dynamic desde next
import { Store } from "../utils/Store";

// Carga dinámica de OffcanvasContent
const OffcanvasContent = dynamic(() => import("./OffcanvasContent"), {
  ssr: false,
});

export default function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);
  const { cart } = state;

  const [cartItemsCount, setCartItemsCount] = useState(0);
  const [bootstrapLoaded, setBootstrapLoaded] = useState(
    typeof window !== "undefined" && window.bootstrapLoaded
  );

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
  }, [cart.cartItems]);

  const openOffcanvas = async () => {
    try {
      // Importa Bootstrap solo en el lado del cliente si no está cargado
      if (typeof window !== "undefined" && !window.bootstrapLoaded) {
        const bootstrap = await import(
          "bootstrap/dist/js/bootstrap.bundle.min.js"
        );
        console.log("Bootstrap loaded");
        window.bootstrap = bootstrap;
        window.bootstrapLoaded = true;
      }

      // Verifica si `window.bootstrap` está definido antes de crear Offcanvas
      if (typeof window !== "undefined" && window.bootstrap) {
        const offcanvas = new window.bootstrap.Offcanvas(
          document.getElementById("offcanvasRight")
        );
        offcanvas.show();
      }
    } catch (error) {
      console.error("Error loading Bootstrap:", error);
    }
  };

  return (
    <div>
      <Head>
        <title>{title ? title + "- tienda" : "tienda"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
        <div className="container">
          <Link className="navbar-brand" href="/">
            Storage
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav ms-auto">
              <li className="nav-item">
                {/* Abre el offcanvas al hacer clic en el enlace del carrito */}
                <a
                  href="javascript:void(0);"
                  className="nav-link"
                  onClick={openOffcanvas}
                >
                  Cart{" "}
                  <span className="text-white bg-danger rounded p-1">
                    {cartItemsCount}
                  </span>{" "}
                </a>
              </li>

              <li className="nav-item">
                <Link className="nav-link" href="">
                  Others
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <main>{children}</main>

      {/* Offcanvas */}
      <OffcanvasContent />
    </div>
  );
}
