const data = {
  products: [
    {
      name: "Jersey Boca Jrs",
      type: "Football",
      price: "60",
      patent: "Adidas",
      category: "Top",
      gender: "Men",
      slug: "Jersey Boca Jrs",
      image: "/images/remeram1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Jersey River Plate",
      type: "Football",
      price: "60",
      patent: "Adidas",
      category: "Top",
      gender: "Men",
      slug: "Jersey River Plate",
      image: "/images/remeram2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Hoodie Argentina",
      type: "Football",
      price: "70",
      patent: "Adidas",
      category: "Top",
      gender: "Men",
      slug: "Hoodie Argentina",
      image: "/images/buzom1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Hoodie Grey",
      type: "Training",
      price: "45",
      patent: "Nike",
      category: "Top",
      gender: "Men",
      slug: "Hoodie Grey",
      image: "/images/buzom2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Short Boca Juniors",
      type: "Football",
      price: "25",
      patent: "Adidas",
      category: "Bottom",
      gender: "Men",
      slug: "Short Boca Juniors",
      image: "/images/shortm1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Short River Plate",
      type: "Football",
      price: "25",
      patent: "Adidas",
      category: "Bottom",
      gender: "Men",
      slug: "Short River Plate",
      image: "/images/shortm2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Athletic Pants Argentina",
      type: "Football",
      price: "50",
      patent: "Adidas",
      category: "Bottom",
      gender: "Men",
      slug: "Athletic Pants Argentina",
      image: "/images/pantalonm1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Athletic Pants",
      type: "Training",
      price: "30",
      patent: "Under Armour",
      category: "Bottom",
      gender: "Men",
      slug: "Athletic Pants",
      image: "/images/pantalonm2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Urban",
      price: "45",
      patent: "Adidas",
      category: "Shoes",
      gender: "Men",
      slug: "Shoes",
      image: "/images/shoesm1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "50",
      patent: "Nike",
      category: "Shoes",
      gender: "Men",
      slug: "Shoes",
      image: "/images/shoesm2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "75",
      patent: "Nike",
      category: "Shoes",
      gender: "Men",
      slug: "Shoes",
      image: "/images/shoesm3.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "40",
      patent: "Puma",
      category: "Shoes",
      gender: "Men",
      slug: "Shoes",
      image: "/images/shoesm4.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shirt Lila",
      type: "Training",
      price: "20",
      patent: "Topper",
      category: "Top",
      gender: "Women",
      slug: "Shirt Lila",
      image: "/images/remeraw1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shirt Black",
      type: "Training",
      price: "25",
      patent: "Fila",
      category: "Top",
      gender: "Women",
      slug: "Shirt Black",
      image: "/images/remeraw2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Hoodie Black",
      type: "Training",
      price: "30",
      patent: "Fila",
      category: "Top",
      gender: "Women",
      slug: "Hoodie Black",
      image: "/images/buzow1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Hoodie Red",
      type: "Training",
      price: "40",
      patent: "Under Armour",
      category: "Top",
      gender: "Women",
      slug: "Hoodie Red",
      image: "/images/buzow2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Short",
      type: "Training",
      price: "20",
      patent: "Under Armour",
      category: "Bottom",
      gender: "Women",
      slug: "Short",
      image: "/images/shortw1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Skort",
      type: "Training",
      price: "40",
      patent: "Adidas",
      category: "Bottom",
      gender: "Women",
      slug: "Skort",
      image: "/images/shortw2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Athletic Leggings",
      type: "Training",
      price: "55",
      patent: "Under Armor",
      category: "Bottom",
      gender: "Women",
      slug: "Athletic Leggings",
      image: "/images/calzaw1.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Athletic Leggings",
      type: "Training",
      price: "20",
      patent: "Puma",
      category: "Bottom",
      gender: "Women",
      slug: "Athletic Leggings",
      image: "/images/calzaw2.jpg",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "45",
      patent: "Adidas",
      category: "Shoes",
      gender: "Women",
      slug: "Shoes",
      image: "/images/shoesw1.png",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "55",
      patent: "Adidas",
      category: "Shoes",
      gender: "Women",
      slug: "Shoes",
      image: "/images/shoesw2.png",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "75",
      patent: "Adidas",
      category: "Shoes",
      gender: "Women",
      slug: "Shoes",
      image: "/images/shoesw3.png",
      countInStock: 20,
      description: "",
    },
    {
      name: "Shoes",
      type: "Running",
      price: "40",
      patent: "Adidas",
      category: "Shoes",
      gender: "Women",
      slug: "Shoes",
      image: "/images/shoesw4.jpg",
      countInStock: 20,
      description: "",
    },
  ],
};

export default data