import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import ProductItem from "../components/ProductItem";
import data from "../utils/data";
import BootstrapCarousel from "../components/Carousel";
import Card from "../components/Card";
import { renderProductCategory } from "../utils/ProductUtils";
import Link from "next/link";


export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <title>Next.js Carousels</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout title={"home page"}></Layout>
        <main>
          <BootstrapCarousel />
        </main>
      </div>
      <div>
        <h2 className="text-center mt-5 mb-5">Shop</h2>
        <Card />
      </div>
      <div>
        <h2 className="text-center mt-5 mb-5">List of products</h2>
        <div className="container">
          <h2 className="text-center mt-5 mb-5" id="men-section">Men</h2>
          {renderProductCategory("Men", "Top")}
          {renderProductCategory("Men", "Bottom")}
          {renderProductCategory("Men", "Shoes")}
          <h2 className="text-center mt-5 mb-5" id="women-section" >Women</h2>
          {renderProductCategory("Women", "Top")}
          {renderProductCategory("Women", "Bottom")}
          {renderProductCategory("Women", "Shoes")}
        </div>
      </div>
    </div>
  );
}
