import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import ProductItem from "../components/ProductItem";
import data from "../utils/data";
import BootstrapCarousel from "../components/Carousel";
import Card from "../components/Card";


export default function Home() {
  return (
    <div>
      <div>
        <Head>
          <title>Next.js Carousels</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout title={"home page"}></Layout>
        <main>
          <BootstrapCarousel />
        </main>
      </div>
      <div>
        <h2 className="text-center mt-5 mb-5">Shop</h2>
        <Card />
      </div>
      <div>
        <h2 className="text-center mt-5 mb-5">List of products</h2>
        <div className="container">
          <div className="row row-cols-1 row-cols-md-2 g-4">
            {data.products.map((product) => (
              <ProductItem key={product.slug} product={product} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
